name: golf_coach
description: Random shot generator + logging + insights for golf improvement.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  flutter_riverpod: ^2.3.6
  flutter_material_pickers: ^3.0.0
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  drift_dev: ^2.18.0
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/custom_club_distances.json
